#!/bin/sh
#
# copy over NTP configuration
#

set -e

. /usr/sbin/resin-vars

if [ ! -f "$CONFIG_PATH" ]; then
	echo "resin-ntp-config: $CONFIG_PATH does not exist."
	exit 1
else
	echo "resin-ntp-config: Found config.json in $CONFIG_PATH ."
fi

if [ ! -z "$NTP_SERVERS" ]; then
	for ntp in ${NTP_SERVERS}; do
		# Resolve to an IP address in case of using NTP pools
#		ntpsource=$(ping -c1 "${ntp}" | tr -d '():' | awk '/^PING/{print $3}')
		ntpsource=$(/usr/bin/getent ahostsv4 "${ntp}" | tail -1 | awk '{ print $1 }')
		/usr/bin/chronyc add server "${ntpsource}" minpoll 14 maxpoll 14 || true
		/usr/bin/chronyc burst 4/10 "${ntpsource}" || true
	done
fi

exit 0
